<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Collection as Collection;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\URL;


class Ad extends Model
{
    //protected $dateFormat = 'd-m-Y H:i:s';
    protected $fillable = [
        'name', 'slug', 'images', 'location', 'description', 'price', 'category_id', 'user_id', 'ip', 'seller_type', 'parent_id'
    ];
    use Sluggable;

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    public function user(){
        return $this->belongsTo('\App\User');
    }
    public function category(){
        return $this->belongsTo('\App\Category');
    }

    public static function descendants($category, Collection $ads){
        /*if($ads->count() == 0){
            $ads->push($category->ads);
        }
        else{
            $ads->push($category->ads);
            foreach ($category->children as $child){
                self::descendants($child, $ads);
            }
        }
        return $ads;*/

    }

    public function getURL($action){
        return URL::temporarySignedRoute(
            'ads.'.$action,
            now()->addDays(1),
            ['ad' => $this]
        );
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function($ad){
            if($ad->images != '/img/no-image.png')
            Storage::delete(json_decode($ad->images));
        });
//        static::updated(function($ad){
//            $images = json_decode($ad->images);
//            foreach ($images as $key => $image){
//                if($image == '/img/no-image.png'){
//                    unset($images[$key]);
//                }
//            }
//            $ad->images = json_encode($images);
//            $ad->save();

//        });
    }
}
